apiVersion: v1
kind: Namespace
metadata:
  name: kuma-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuma-deployment
  namespace: kuma-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upku
  template:
    metadata:
      labels:
        app: upku
    spec:
      containers:
      - name: uptime-kuma
        image: louislam/uptime-kuma:1
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: kuma-svc
  namespace: kuma-ns
spec:
  selector:
    app: upku
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3001
  type: LoadBalancer
